### ISSUE TITLE
開伺服一段時間自動關閉

### ISSUE THREAD

**Issue by s3df6rwe** [XUAN-Cat/Season#1]
[crash-2019-06-15_01.15.01-server.txt](https://github.com/XUAN-Cat/Season/files/3291580/crash-2019-06-15_01.15.01-server.txt)

**Comment by XUAN-Cat** [comment]
已經嘗試修復此問題
https://github.com/XUAN-Cat/Season/releases/tag/v1.0.1
在嘗試看看
