### ISSUE TITLE
崩潰

### ISSUE THREAD

**Issue by s3df6rwe** [XUAN-Cat/Season#2]
[crash-2019-06-15_04.10.47-server.txt](https://github.com/XUAN-Cat/Season/files/3292080/crash-2019-06-15_04.10.47-server.txt)
我好像都打ess home蹦潰了

**Comment by XUAN-Cat** [comment]
https://github.com/XUAN-Cat/Season/releases/tag/v1.0.2
由於錯誤報告沒有明確顯示是季節插件的錯誤,再不行的話,可能主要原因不再季節插件

**Comment by XUAN-Cat** [comment]
我使用 EssentialsX-2.16.1.0 測試,目前沒發生問題
